name: amal_charity
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  hexcolor: ^3.0.1
  http: ^0.13.6
  provider: ^6.0.5
  carousel_slider: ^4.2.1
  url_launcher:
  animated_splash_screen:
  go_router:
  pdf:
  path_provider:
  open_file: ^3.3.2


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/homescreen/
  fonts:
    - family: Janna
      fonts:
        - asset: assets/fonts/Janna.ttf
flutter_intl:
  enabled: true
